### ISSUE TITLE
Rig fails to initialize on 4.0

### ISSUE THREAD

**Issue by zayJax** [hisprofile/rigi-all#3]
Used to work like a charm on previous versions, but it seems that the changes to the Bone Layers in 4.0 broke this add-on.
Now, when initializing the rig, i get the following error:

```
Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\rigi-all\__init__.py", line 437, in execute
    bpy.ops.pose.rigify_layer_init()
  File "C:\Users\name\Documents\blender-4.0.0-stable+v40.878f71061b8e-windows.amd64-release\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.pose.rigify_layer_init" error, could not be found
```

**Comment by Gabe-JAMs** [comment]
Know it's an old post but the error is still present
